apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.phase }}-{{ $.Values.projectName }}
  labels:
    app: {{ $.Values.phase }}-{{ $.Values.projectName }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Values.phase }}-{{ $.Values.projectName }}
  template:
    metadata:
      labels:
        app: {{ $.Values.phase }}-{{ $.Values.projectName }}
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
    spec:
      {{- if .Values.appMesh.fargatePodServiceAccount }}
      serviceAccountName: {{ .Values.appMesh.fargatePodServiceAccount }}
      securityContext:
        fsGroup: 1337
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          env:
            {{- range $key, $value := .Values.backend.envAddresses }}
            - name: {{ $key }}
              value: {{ template "backendUrl" (dict "appMeshEnabled" $.Values.appMesh.enabled "backendAddress" $value "namespace" $.Release.Namespace) }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            {{- $root := . }}
            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref }}_{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.phase }}-{{ $.Values.projectName }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
