{{- if and (.Values.appMesh.enabled) (.Values.appMesh.outsideTrafficAllowed) -}}
{{- $fullName := include "application.fullname" . -}}
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: {{ $.Values.phase }}-{{ $.Values.projectName }}
  labels:
    app: {{ $.Values.phase }}-{{ $.Values.projectName }}
spec:
  httpRoute:
    match:
      prefix: {{ .Values.appMesh.gatewayRouteMatchPrefix | default (printf "/%s" $fullName) }}
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: {{ $.Values.phase }}-{{ $.Values.projectName }}
{{- end -}}
