apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.phase }}-{{ $.Values.projectName }}
  labels:
    app: {{ $.Values.phase }}-{{ $.Values.projectName }}
  namespace: {{ $.Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.portName }}
      name: {{ .Values.service.portName }}
      {{- end }}
      targetPort: {{ .Values.deployment.containerPort }}
      protocol: TCP

  selector:
    app: {{ $.Values.phase }}-{{ $.Values.projectName }}
